#!/bin/bash

# spkg - Sourim Package Manager
# Copyright (C) 2024 r2u2team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ARCH=`uname -m`
ROOT=

args=
depends=
dependsVersion=()
packagesJobs=

show_help() {
    echo "Usage: $0 (install | update | rindex [-a arch]) [-r root_path] [PACKAGEs]"
    exit 1
}
show_err() {
    echo "Error: $@"
    exit 1
}
download_thread() {
    if [ -z $2 ]; then
        wget -q --show-progress $1 &
    else
        wget -q --show-progress $1 -O $2 &
    fi
}
get_depends() {
    while read line; do
        line=(${line})
        if [ "${line[0]}" == $1 ]; then
            for pkg in ${line[@]:2}; do
                get_depends $pkg
            done
            depends+="$1 "
        fi
    done < "$ROOT/var/spkg/$ARCH-info"
}
fetch_depends() {
    unset depends
    dependsVersion=()
    echo "Calculating dependencies..."

    for pkg in $@; do
        get_depends $1
    done

    depends=`echo $depends | tr ' ' '\n' | awk '{if (!h[$0]) h[$0]=NR} END {for (k in h) {print h[k],k}}' | sort -k1n | cut -d' ' -f2-`
    for pkg in $depends; do
        while read line; do
            line=(${line})
            if [ "${line[0]}" == $pkg ]; then
                dependsVersion+=("${line[1]}")
            fi
        done < "$ROOT/var/spkg/$ARCH-info"
    done
}

if [ -z "$1" ] || [ -z "2" ]; then
    show_help
fi

# Options
for (( i=2; i <= $#; i++ )); do
    if [ "${!i}" == "-r" ]; then
        ((i++))
        ROOT=${!i}
    elif [ "${!i}" == "-a" ]; then
        ((i++))
        ARCH=${!i}
    else
        args+=${!i}
    fi
done

mkdir -p $ROOT/{etc,var/spkg/cache} || show_err "Create dirs"
if [ ! -f "$ROOT/etc/spkg.conf" ]; then
    cp default/spkg.conf $ROOT/etc/ || show_err "Copy default config to '$ROOT/etc/'"
fi
. $ROOT/etc/spkg.conf || show_err "Loading config"

# Commands
# tar -axf $pkg pkginfo -O > /tmp/spkg-pkginfo
case $1 in
    "update")
        for repo in $repos; do
            while [[ `jobs | wc -l` -ge $parallelDownload ]]; do sleep 1; done
            download_thread "$repo/$ARCH-info" "/tmp/$ARCH-info" || show_err "Download repos"
        done
        wait

        xz -dc "/tmp/$ARCH-info" > "$ROOT/var/spkg/$ARCH-info" || show_err "Decompress '$ARCH-info' data"
    ;;
    "install")
        if [ ! -f "$ROOT/var/spkg/$ARCH-info" ]; then
            show_err "'$ARCH-info' is not exist. Please enter '$0 update' to update the list of packages"
        fi

        fetch_depends $args

        echo "Packages to be installed:"
        if [ "$verboseList" == "y" ]; then
            echo -e "NAME\t\tVERSION"
            ((i=0))
            for pkg in $depends; do
                echo -e "$pkg\t\t${dependsVersion[$((i))]}"
                ((i++))
            done
        else
            echo "$depends"
        fi

        read -p "Are you sure you want to install packages?(Y/n): " confirm
        if [ "$confirm" != "y" ] && [ ! -z "$confirm" ]; then
            exit 1
        fi

        # Download packages
        ((COUNTPKGS=0))
        OUTFILES=()
        for pkg in $depends; do
            while [[ `jobs | wc -l` -ge $parallelDownload ]]; do sleep 1; done

            OUTFILE="$ROOT/var/spkg/cache/$pkg-${dependsVersion[$COUNTPKGS]}-$ARCH.tar"
            OUTFILES+="$OUTFILE "
            download_thread "${repos[0]}/$pkg-${dependsVersion[$COUNTPKGS]}-$ARCH.tar" "$OUTFILE" || show_err "Download packages"
            ((COUNTPKGS++))
        done
        wait

        ((i=0))
        for pkg in $OUTFILES; do
            echo "[$((i))/$COUNTPKGS] Unpacking '$(basename $pkg)'..."

            OUTDIR="/tmp/spkg-$RANDOM"
            mkdir -p $OUTDIR

            tar xf "$pkg" -C $OUTDIR || show_err "Unpacking temp package"
            tar xf "$OUTDIR/rootfs.tar.xz" -C $ROOT || show_err "Unpacking package"

            ((i++))
        done
        
        echo "Clear temp files..."
        rm -rf /tmp/spkg-* || show_err "Remove temp files"
        rm -rf "$ROOT/var/spkg/cache/*" || show_err "Remove temp packages"
    ;;
    "rindex")
        echo -n > /tmp/spkg-pkglist || show_err "Write pkglist"

        for pkg in ${@:2}; do
            tar -axf $pkg pkginfo -O > /tmp/spkg-pkginfo || show_err "Read 'pkginfo' from package"
            . /tmp/spkg-pkginfo || show_err "Apply 'pkginfo' from package"
            echo "$pkgname $pkgversion $pkgdepends" >> /tmp/spkg-pkglist || show_err "Write pkglist"
        done

        xz -zc /tmp/spkg-pkglist > $ARCH-info
    ;;
    *)
        show_help
    ;;
esac