# SourimLinux Default x86_64
verboseList=y         # set the value to "y" to display a detailed list of packages
parallelDownload=10   # set the value to 1 for one thread

repos=(
    "https://sourimlinux.github.io/sourimpkg/x86_64"
) # for now you can only specify one repository